version: '3'

services:
  app: 
    image: php:7.4-fpm 
    volumes:
      - ./:/var/www
    networks:
      - net01

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net01

networks:
  net01:
      driver: bridge